application: gdg2016-debate-sentiment
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

# For the site

- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js
